
# This is a basic workflow to help you get started with Actions

name: entities:0.0

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string : 
#    weekly #m h d/m m d/w 
    - cron:  '10 1 * * 1'
#    daily #m h d/m m d/w 
#    - cron:  '30 1 * * *'
   
jobs:
  docker-run-action:
    runs-on: ubuntu-latest
    container:
      image: tamboraorg/crecoding:2020.0
      volumes:
        - ${{ github.workspace }}:/cre/python
    steps:
      - uses: actions/checkout@v3
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
#        with:
#          ref: main
      - name: cd /cre/python/
        run: (cd /cre/python/)
      - name: Install spacy textblob_de
        run: (pip3 install spacy textblob_de nltk)
      - name: Install download de_core_news_md
        run: (python3 -m spacy download de_core_news_md)
      - name: Run entities
        run: (python3 entities.py)
      - name: Submit changes       
        uses: EndBug/add-and-commit@v9
        with:
#          pull: '--rebase --autostash ...'
          add: 'csv/sentiments_*.csv'
          tag_push: '--force'
